export ZDOTDIR=$HOME/.zsh
export ZPLUG_HOME=$ZDOTDIR/zplug

source $ZDOTDIR/COMPLETION

source $ZDOTDIR/PLUGINS
source $ZDOTDIR/PLUG-SETTINGS

source $ZDOTDIR/PATH
source $ZDOTDIR/COMMANDS
source $ZDOTDIR/ENVIRONMENTS
source $ZDOTDIR/npm_completion
