#!/bin/zsh
alias l="ls -lG"
alias la="ls -lGa"
alias vi="nvim"
alias vim="nvim"
alias py="python3"
alias tk="tmux kill-session -t"

# CLI chrome
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
alias chrome-beta="/Applications/Google\ Chrome\ Beta.app/Contents/MacOS/Google\ Chrome --user-data-dir=$HOME/chromebeta"
alias chrome-canary="/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary"
alias chromium="/Applications/Chromium.app/Contents/MacOS/Chromium"
alias chrome-headless="chrome --headless --disable-gpu"

# tools
alias reload="exec -l $SHELL"
alias clock="tty-clock -DnsC 7"
alias tk="tmux kill-session -t"
alias docker-clean="docker rm $(docker ps -aq)"

# instant fish
function docker-clean-img () {
    for image in $(docker images | grep none | tr -s " " | cut -f3 -d" ")
    do
        docker rmi "$image"
    done
}
