#!/bin/zsh
alias l="ls -lG"
alias la="ls -lGa"
alias vi="vim"
alias py="python"
alias tk="tmux kill-session -t"

alias stime="/usr/bin/time -p"
alias reload="exec -l $SHELL"
alias randgen="openssl rand -base64"
