#!/bin/zsh
# ===============
#    FUNCTIONS
# ---------------
# autoload -Uz emacs
autoload -Uz weather

# auto-fu
source $ZDOTDIR/plugins/auto-fu.zsh/auto-fu.zsh
function zle-line-init () {
    auto-fu-init
}
zle -N zle-line-init
# hide "-azfu-"
zstyle ':auto-fu:var' postdisplay $''
