#!/bin/zsh
# ================
#    COMPLETION
# ----------------
autoload -U compinit
compinit -u

setopt hist_expand
setopt hist_ignore_all_dups
setopt hist_reduce_blanks
setopt hist_no_store
setopt hist_verify
setopt share_history
setopt append_history
zstyle ':completion:*' use-cache yes
zstyle ':completion:*' cache-path ~/.zsh/cache
zstyle ':completion:*' verbose yes
