#!/bin/zsh
# ==============
#    ENCODING
#---------------
export LANG=ja_JP.UTF-8

# =============
#    HISTORY
#--------------
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=500
setopt hist_ignore_dups
setopt share_history


# ============
#    COLORS
#-------------
autoload colors
# dir simlink sock que exec block char uid gid sticky unwritable
# a:black b:red c:green d:brown e:blue f:magenta g:cyan h:white x:none
# uppercase to bold
export LSCOLORS=cxfxdxgfbxfxfxdxDxxBxB


# ============
#    PROMPT
#-------------
setopt prompt_subst
PROMPT='%F{yellow}%n %.%f $ '
PROMPT2='%_ ... '
RPROMPT='%1(v|%F{yellow}%1v%f|)'
RPROMPT+=' %y%F{cyan}@%f%(?,%F{green},%F{red})%m%f'
RPROMPT+=' [%f%F{blue}${ZSH_PYTHON_PROMPT}%f]'
SPROMPT='You mean %r? [n, y, a, e]: '


# ==============
#    BROWSING
#---------------
setopt auto_cd
setopt auto_pushd
setopt correct
setopt list_packed
setopt nolistbeep
setopt nobeep
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' list-colors $LSCOLORS


# =========
#    VCS
#----------
autoload -Uz vcs_info
zstyle ':vcs_info:*' formats '(%b)' # %b: branch information
zstyle ':vcs_info:*' actionformats '(%b|%a)' # %a: action information
precmd () {
    psvar=()
    LANG=en_US.UTF-8 vcs_info
    [[ -n "$vcs_info_msg_0_" ]] && psvar[1]="$vcs_info_msg_0_"
}


# ==============
#    HOMEBREW
# --------------
case `uname` in
    'Darwin')
        export HOMEBREW_CASK_OPTS="--caskroom=/opt/homebrew-cask/Caskroom"
esac
