#!/bin/zsh
# ==============
#    ENCODING
#---------------
export LANG=en_US.UTF-8

# =============
#    HISTORY
#--------------
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=1000


# ============
#    COLORS
#-------------
export TERM=xterm-256color
autoload colors
# dir simlink sock que exec block char uid gid sticky unwritable
# a:black b:red c:green d:brown e:blue f:magenta g:cyan h:white x:none
# uppercase to bold
export LSCOLORS=cxfxdxgfbxfxfxdxDxxBxB


# ============
#    PROMPT
#-------------
setopt prompt_subst
PROMPT='%(?,%F{green}._.,%F{red};_;)%f %F{yellow}%.%f ❯❯❯ '
PROMPT2='%_ ... '
RPROMPT='%1(v|%F{yellow}%1v%f|)'
RPROMPT+=' %D %*'
SPROMPT='You mean %r? [n, y, a, e]: '


# ==============
#    BROWSING
#---------------
setopt auto_cd
setopt auto_pushd
setopt correct
setopt list_packed
setopt nolistbeep
setopt nobeep

# divide words with /
WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'


# =========
#    VCS
#----------
autoload -Uz vcs_info
zstyle ':vcs_info:*' formats '(%b)' # %b: branch information
zstyle ':vcs_info:*' actionformats '(%b|%a)' # %a: action information
precmd () {
    psvar=()
    LANG=en_US.UTF-8 vcs_info
    [[ -n "$vcs_info_msg_0_" ]] && psvar[1]="$vcs_info_msg_0_"
}
