#!/bin/zsh
typeset -U path cdpath fpath manpath PATH
export PYENV_ROOT=$HOME/.pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

autoload -U compinit
compinit -u
