#!/bin/zsh
source $ZPLUG_HOME/init.zsh

# zplug "zplug/zplug"
# completions
zplug "zsh-users/zsh-completions"
zplug "felixr/docker-zsh-completion"
zplug "maxmellon/yarn_completion"
# incremental search
zplug "hchbaw/auto-fu.zsh", at:pu
# bunch of tools
zplug "matsub/zshtools", from:bitbucket

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load --verbose
