#!/bin/zsh
# =============
#    auto-fu
# -------------
function zle-line-init () {
    auto-fu-init
}
zle -N zle-line-init
# hide "-azfu-"
zstyle ':auto-fu:var' postdisplay $''

# =======================
#    zsh-python-prompt
# -----------------------
zstyle ':zsh-python-prompt:pyenv:' symbol ''
