#!/usr/bin/env zsh

echo -n "Are you sure? [y/n]: "
read ans
if [[ ! $ans =~ [yY] ]]; then
    echo "OK. It's cool."
    return;
fi

echo -n "Would you like to open it with vim?[y/n]: "
read ans
if [[ $ans =~ [yY] ]]; then
    vim $@
    return;
fi

echo -n "Another editor? How about nano?[y/n]: "
read ans
if [[ $ans =~ [yY] ]]; then
    nano $@
else
    /usr/bin/emacs $@
fi
